apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: compliance
    app.kubernetes.io/managed-by: kustomize
  name: compliance-controller-manager-metrics
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: compliance
    app.kubernetes.io/name: compliance
