//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *ComplianceProfile) DeepCopyInto(out *ComplianceProfile) {
	*out = *in
	if in.DataCategories != nil {
		in, out := &in.DataCategories, &out.DataCategories
		*out = make([]DataCategory, len(*in))
		copy(*out, *in)
	}
	if in.DataSubjectTypes != nil {
		in, out := &in.DataSubjectTypes, &out.DataSubjectTypes
		*out = make([]DataSubjectType, len(*in))
		copy(*out, *in)
	}
	if in.ProcessingRegions != nil {
		in, out := &in.ProcessingRegions, &out.ProcessingRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EffectiveDate != nil {
		in, out := &in.EffectiveDate, &out.EffectiveDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new ComplianceProfile.
func (in *ComplianceProfile) DeepCopy() *ComplianceProfile {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *Subprocessor) DeepCopyInto(out *Subprocessor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new Subprocessor.
func (in *Subprocessor) DeepCopy() *Subprocessor {
	if in == nil {
		return nil
	}
	out := new(Subprocessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *Subprocessor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *SubprocessorDisclosure) DeepCopyInto(out *SubprocessorDisclosure) {
	*out = *in
	if in.DataCategories != nil {
		in, out := &in.DataCategories, &out.DataCategories
		*out = make([]DataCategory, len(*in))
		copy(*out, *in)
	}
	if in.ProcessingRegions != nil {
		in, out := &in.ProcessingRegions, &out.ProcessingRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EffectiveDate != nil {
		in, out := &in.EffectiveDate, &out.EffectiveDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new SubprocessorDisclosure.
func (in *SubprocessorDisclosure) DeepCopy() *SubprocessorDisclosure {
	if in == nil {
		return nil
	}
	out := new(SubprocessorDisclosure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *SubprocessorList) DeepCopyInto(out *SubprocessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subprocessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new SubprocessorList.
func (in *SubprocessorList) DeepCopy() *SubprocessorList {
	if in == nil {
		return nil
	}
	out := new(SubprocessorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *SubprocessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *SubprocessorSpec) DeepCopyInto(out *SubprocessorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new SubprocessorSpec.
func (in *SubprocessorSpec) DeepCopy() *SubprocessorSpec {
	if in == nil {
		return nil
	}
	out := new(SubprocessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *SubprocessorStatus) DeepCopyInto(out *SubprocessorStatus) {
	*out = *in
	if in.Disclosure != nil {
		in, out := &in.Disclosure, &out.Disclosure
		*out = new(SubprocessorDisclosure)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new SubprocessorStatus.
func (in *SubprocessorStatus) DeepCopy() *SubprocessorStatus {
	if in == nil {
		return nil
	}
	out := new(SubprocessorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *Vendor) DeepCopyInto(out *Vendor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new Vendor.
func (in *Vendor) DeepCopy() *Vendor {
	if in == nil {
		return nil
	}
	out := new(Vendor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *Vendor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *VendorList) DeepCopyInto(out *VendorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vendor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new VendorList.
func (in *VendorList) DeepCopy() *VendorList {
	if in == nil {
		return nil
	}
	out := new(VendorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *VendorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *VendorSpec) DeepCopyInto(out *VendorSpec) {
	*out = *in
	if in.ComplianceProfile != nil {
		in, out := &in.ComplianceProfile, &out.ComplianceProfile
		*out = new(ComplianceProfile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new VendorSpec.
func (in *VendorSpec) DeepCopy() *VendorSpec {
	if in == nil {
		return nil
	}
	out := new(VendorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *VendorStatus) DeepCopyInto(out *VendorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new VendorStatus.
func (in *VendorStatus) DeepCopy() *VendorStatus {
	if in == nil {
		return nil
	}
	out := new(VendorStatus)
	in.DeepCopyInto(out)
	return out
}
