apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: compliance
    app.kubernetes.io/managed-by: kustomize
  name: compliance-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compliance-leader-election
subjects:
- kind: ServiceAccount
  name: compliance-controller-manager
